version: '3'
services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../ssl/cwrcoding.com:/etc/nginx/ssl:ro
      - acme_challenge:/etc/nginx/acme_challenge:ro
      - ./files:/etc/nginx/files:ro
      - ./sites-available:/etc/nginx/sites-available:ro
      - ./static_config:/etc/nginx/static_config:ro
      - ./sites-enabled:/etc/nginx/sites-enabled:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    network_mode: "host"

volumes:
  acme_challenge:
    external: true
